name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP 8
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: none, mbstring, dom, xml, libxml, json, xmlwriter

    - name: check docker version && pull hello-world image.
      run: docker -v && docker pull hello-world

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install guzzlehttp/psr7
      run: composer require guzzlehttp/psr7

    - name: Run test suite
      run: composer run-script test
